"""
Django settings for demsense project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from hiver.conf.base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ENVIRONMENT = "local"

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
    }
}

LOGGING = {
    'version': 1,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'request_id': {
                '()': 'log_request_id.filters.RequestIDFilter'
        },
    },
    'formatters': {
            'verbose': {
                'format': "[%(asctime)s] %(levelname)s [%(request_id)s] [%(name)s:%("
                          "lineno)s] %(""message)s",
                'datefmt': "%d/%b/%Y %H:%M:%S"
            },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true', 'request_id'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        }
    },
    'loggers': {
        'hiver.apps.base': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'hiver.apps.api': {
            'handler': ['console'],
            'level': 'INFO',
        },
        # 'django.db.backends': {
        #     'level': 'DEBUG',
        #     'handlers': ['console'],
        # },
    }
}
